<?php
/**
 * @file
 * Zurb Foundation 6 grid plugin for views.
 */

/**
 * Implements hook_autoload_info.
 */
function views_z6_full_autoload_info() {
  return array(
    'views_plugin_style_views_z6_full' => 'views_plugin_style_views_z6_full.inc',
  );
}

/**
 * Implements hook_views_api()
 */
function views_z6_full_views_api() {
  return array(
    'api' => '3.0',
    'path' => backdrop_get_path('module', 'views_z6_full'),
    'template_path' => backdrop_get_path('module', 'views_z6_full'),
  );
}

/**
 * Preprocess function for views_view_views_z6_full.tpl.php.
 */
function template_preprocess_views_view_views_z6_full(&$vars) {
  // Run preprocess function for unformatted style
  template_preprocess_views_view_unformatted($vars);
  // Get view options
  $view = $vars['view'];
  $options = $vars['options'];
}
